title: Veles Documentation
description: Documentation for the Veles UI library
theme: just-the-docs

url: https://bloomca.github.io/veles

aux_links:
  Template Repository: https://github.com/bloomca/veles
