name: pull-request-workflow
run-name: Veles PR checks
on: [pull_request]

permissions:
  actions: read
  contents: read
  packages: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - uses: action/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run test
