name: pull-request-workflow
run-name: Veles PR checks
on: [pull_request]

permissions:
  actions: read
  contents: read
  packages: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4
        with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0

